# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
workflows:
    build:
      jobs:
        - build
  # Name the workflow "welcome"
      
jobs:
  build:
    docker:
      - image: node:alpine
    environment:
      FOO: bar
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: docker build .
